In [2]:
import torch

In [3]:
data = [[1., 2],[3, 4]]
x_data = torch.tensor(data)
x_data.dtype

# 默认为float32

torch.float32

In [4]:
# 转换为float64的代码 
x_data = x_data.to(torch.float64)
x_data.dtype

torch.float64

In [5]:
# zeros_like 和 ones_like
x_ones = torch.ones_like(x_data)
x_zeros = torch.zeros_like(x_data)
print(x_ones)
print(x_zeros)

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)
tensor([[0., 0.],
        [0., 0.]], dtype=torch.float64)


In [6]:
# Attributes of a Tensor
tensor = torch.rand(3,4)
tensor

tensor([[0.5305, 0.7095, 0.1565, 0.3488],
        [0.1306, 0.6309, 0.9787, 0.2538],
        [0.2123, 0.3929, 0.1988, 0.1354]])

In [7]:
# dtype shape device 张量的数据类型，形状，加载设备
print(tensor.dtype, tensor.shape, tensor.device)

torch.float32 torch.Size([3, 4]) cpu


In [8]:
# Operations on Tensors 加载到gpu上
if torch.cuda.is_available():
    tensor = tensor.to('cuda')
    print(tensor.device)

cuda:0


In [9]:
# 常见用法
torch.is_tensor(tensor)

True

In [17]:
# torch.is_nonzero(tensor) # 判断是否为非零张量
# 只能用于一个张量元素的运算
a = torch.tensor(1.)
print(torch.is_nonzero(a))
# 下面是一个错误的例子
# b = torch.tensor([1, 0])
# print(torch.is_nonzero(b))

True


In [22]:
# torch.umel(tensor) # 判断张量元素的个数
# acctually it is tensor.shape 每个元素连乘的结果
a = torch.tensor([[1, 2, 4], [3, 5, 4]])
print(a.shape)
print(torch.numel(a))

torch.Size([2, 3])
6
